language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get update
  - sudo apt-get install libmagic-dev libwebp-dev
  - pip install iiif coveralls pycodestyle pep257
script:
  - pycodestyle --ignore=E501 *.py
  - pep257 *.py
  - python test_book1.py
